variable "aws_account_number" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "vgw_id" {}
variable "vgw_connection_name" {}
variable "bgp_local_as" {}
variable "avx_account_name" {}
variable "avx_controller_ip" {}
variable "avx_controller_username" {}
variable "avx_controller_password" {}
variable "static_transit_vpc_id" {}
variable "static_transit_public_subnet" {}
variable "static_transit_public_ha_subnet" {}
variable "static_transit_gateway_name" {}
variable "static_transit_region" {}
variable "spoke_region" {}
variable "spoke_gateways" {}
variable "spoke_prefix" {}
variable "transit_ec2_instance" {}
variable "spoke_ec2_instance" {}
