variable "aws_account_number" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "account_name" {}
variable "vgw_id" {}
variable "vgw_connection_name" {}
variable "bgp_local_as" {}
variable "controller_ip" {}
variable "controller_username" {}
variable "controller_password" {}
variable "static_transit_vpc_id" {}
variable "static_transit_vpc_net" {}
variable "static_transit_vpc_net2" {}
variable "static_transit_gateway_name" {}
variable "region" {}
variable "spoke_gateways" {}
